### ISSUE TITLE
bower.json "main" section references missing css file

### ISSUE THREAD

**Issue by lowesoftware** [vesparny/angular-fancy-modal#3]
The bower.json "main" section references dist/angular-fancy-modal-theme-default.css. My preference would be to remove the reference from the bower.json file completely rather than have it point to a default css theme file. My grunt bulid process auto-imports the bower.json main files into my SPA and I'd prefer the theme css not be included as the default behavior and rather that I explicitly import a theme css file if I need/want one.

**Comment by vesparny** [comment]
I think this is specific to your project, maybe it's better to handle the issue there.
