### ISSUE TITLE
on close function

### ISSUE THREAD

**Issue by dhawken** [vesparny/angular-fancy-modal#4]
I might be missing something basic, but is there a way to pass a function to open to be called when the dialog is closed non-programmatically (esc or overlay click)?  Or do I have to rely on the event broadcast?  I'm using a controller and it seems its remaining in scope somehow after the dialog is dismissed.  Maybe that's the bigger issue - is the controller scope being destroyed?

**Comment by vesparny** [comment]
Can you post an example?

**Comment by kbaryshnikov** [comment]
Yes, the parent scope is being destroyed, see #5

**Comment by vesparny** [comment]
It's been fixed in version 1.0.4
Let me know
