### ISSUE TITLE
Closing modal results in overlay not dissapearing and error

### ISSUE THREAD

**Issue by PositiveLions** [vesparny/angular-fancy-modal#6]
I'm using angular-1.2.28 and testing in Chrome 42.0.2311.152 m

When I close a modal, either through clicking on the overlay, the X button, pressing escape, or $scope.$modal.close(), the modal dissapears, the overlay dissapears, then the overlay returns and prevents any clicking on the page beneath it.  In Chrome's developer console I also get the error:

Uncaught TypeError: Cannot read property '$destroy' of undefined

This references line 96 of angular-fancy-modal.js
It also affects the minified version.

The line in question is:
$modal.scope.$destroy();

If I comment that line out it seems to work fine, though I feel like it's probably causing a small  memory-leak.

The only parameters I pass to $fancyModal.open() are 'templateUrl', 'controller', and occasionally 'resolve'.

**Comment by vesparny** [comment]
It's been fixed in version 1.0.4
Let me know
